- name: practice playbook
  hosts: all
  remote_user: sysop
  connection: ssh
  become: yes
  tasks:
          - name: create file
            file: 
             path: /tmp/test.txt
             state: touch

          - name: insert
            lineinfile:
                    path: /tmp/test.txt
                    line: " testing purpose "
                    state: present
                    backup: yes


