- name: example of loop 
  hosts: all
  remote_user: sysops
  become: yes
  tasks:
        - name: create file
          file:
                  path: "{{ item }}"
                  state: touch
          with_items: 
                    - /tmp/asdq
