- name: example of loop
  hosts: all
  remote_user: sysops 
  connection: ssh
  become: yes
  vars_files: 
       - /home/sysops/akash_ansible/user.yml
  tasks:
       - name: useradd
         user:
          name:  "{{ item }}"
          state: present
         with_items: "{{ userlist }}"   


