---
- hosts: all
  become: yes
  remote_user: sysops
  tasks:
    - name: add user
      user:
        name: sahkapoo
        state: present
        shell: /bin/bash
        createhome: yes
        password: "{{ pw|password_hash('sha512') }}"
    - name: suoders entry
      lineinfile:
        dest: /etc/sudoers
        line: "sahkapoo  ALL = (ALL) NOPASSWD: /bin/su - jira"
        state: present
        backup: yes
        validate: '/usr/sbin/visudo -cf %s'    
